### ISSUE TITLE
[Feature-request]: Detect a wide variety of non-standard ERC20 tokens

### ISSUE THREAD

**Issue by 0xPhaze** [crytic/properties#23] opened 2023-04-07 11:06 UTC
### Describe the desired feature or improvement

https://github.com/d-xo/weird-erc20#tokens provides a good list of non-standard ERC20 tokens, along with nice example contracts. I think we should aim to integrate these tokens as test-cases and be able to detect a good number of these.

**Comment by montyly** [comment] 2023-04-07 11:49
Duplicate of https://github.com/crytic/properties/issues/20 I think

**Closed** 2023-04-07 11:50 UTC
